### ISSUE TITLE
default value never used in env function

### ISSUE THREAD

**Issue by serge20** [mattstauffer/craftPluginDevHelpers#1]
Hey,

I noticed this in the env method, the default value is never returned whatever the case.

` 
if ($value === false) {
            return $value instanceof Closure ? $value() : $value;
}
`

Shouldn't you be checking for $default instead? 

it should be 

` 
if ($value === false) {
            return $default instanceof Closure ? $default() : $default;
}
`

**Comment by mattstauffer** [comment]
Thanks for catching that @serge20 !
